name: SNLE
run: sbi.snle.run
device: cpu
params:
  num_rounds: 10
  neural_net: maf
  hidden_features: 50
  simulation_batch_size: 1000
  training_batch_size: 10000
  automatic_transforms_enabled: true
  mcmc_parameters:
    num_chains: 100
    thin: 10
    warmup_steps: 100
    # NOTE: sbi API changed. To get the same settings as for the main paper results we
    # have to change init_strategy from "sir" to "resample" and pass the kwargs in a 
    # separate dict.
    # init_strategy: sir
    # sir_batch_size: 1000
    # sir_num_batches: 100
    init_strategy: resample
    init_strategy_parameters:
      num_candidate_samples: 10000
  z_score_x: independent
  z_score_theta: independent